[package]
authors = ["DatenLord <dev@datenlord.io>"]
categories = ["Driver"]
keywords = ["RDMA", "Driver"]
description = "Blue RDMA Driver"
license = "Apache-2.0"
repository = "todo"
name = "blue-rdma-driver"
version = "0.1.0"
edition = "2021"

[features]
default = ["page_size_2m"]
page_size_2m = []
page_size_4k = []

[dependencies]
criterion = "0.5.1"
libc = "0.2.168"
memmap2 = "0.9.5"
