name: Cargo Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libibverbs-dev

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust-driver/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('rust-driver/**/Cargo.lock') }}

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - name: Run tests
      working-directory: rust-driver
      run: cargo nextest run --nocapture

